"""Identity join (M2-T2): StatsBomb player ids -> reep -> Transfermarkt.

reep's bridges table maps provider ids onto stable reep ids: our players sit in
namespace 'offline_player', Transfermarkt players in 'spieler'. No name matching
anywhere — ids only (PLAN §2.4). Manual fixes live in identity_overrides.csv
next to this script and win over the bridge.

Outputs:
  data/identity/player_map.parquet   one row per corpus player, resolved or not
  reports/identity_resolution.md     rates (plain + action-weighted) + top-50
                                     unresolved by actions, for hand-patching
"""

import sys
from pathlib import Path

import duckdb

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "ingest"))
from corpus import ROOT, load_config  # noqa: E402

CFG = load_config()
STAGING = ROOT / CFG["paths"]["staging"] / "statsbomb"
REEP = ROOT / CFG["paths"]["reep"]
TM = ROOT / CFG["paths"]["transfermarkt"]
OVERRIDES = Path(__file__).parent / "identity_overrides.csv"
OUT = ROOT / "data" / "identity" / "player_map.parquet"

if __name__ == "__main__":
    con = duckdb.connect()
    con.sql(f"""
        CREATE VIEW roster AS
        SELECT player_id, any_value(player) AS player, count(*) AS actions
        FROM '{STAGING}/events/*.parquet'
        WHERE player_id IS NOT NULL GROUP BY player_id""")
    con.sql(f"""
        CREATE VIEW sb_bridge AS
        SELECT cast(external_id AS BIGINT) AS player_id, reep_id
        FROM read_csv_auto('{REEP}/bridges.csv.gz')
        WHERE provider = 'statsbomb' AND namespace = 'offline_player'""")
    con.sql(f"""
        CREATE VIEW tm_bridge AS
        SELECT reep_id, cast(external_id AS BIGINT) AS tm_player_id
        FROM read_csv_auto('{REEP}/bridges.csv.gz')
        WHERE provider = 'transfermarkt' AND namespace = 'spieler'""")
    con.sql(f"""
        CREATE VIEW overrides AS
        SELECT cast(sb_player_id AS BIGINT) AS sb_player_id,
               cast(tm_player_id AS BIGINT) AS tm_player_id
        FROM read_csv_auto('{OVERRIDES}', header = true)""")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    con.sql(f"""
        COPY (
            SELECT r.player_id, r.player, r.actions,
                   s.reep_id,
                   coalesce(o.tm_player_id, t.tm_player_id) AS tm_player_id,
                   p.name AS tm_name,
                   CASE WHEN o.tm_player_id IS NOT NULL THEN 'override'
                        WHEN t.tm_player_id IS NOT NULL THEN 'bridge'
                        ELSE NULL END AS resolved_via
            FROM roster r
            LEFT JOIN sb_bridge s USING (player_id)
            LEFT JOIN tm_bridge t USING (reep_id)
            LEFT JOIN overrides o ON o.sb_player_id = r.player_id
            LEFT JOIN '{TM}/players.csv' p
                   ON p.player_id = coalesce(o.tm_player_id, t.tm_player_id)
        ) TO '{OUT}' (FORMAT parquet, COMPRESSION zstd)""")

    m = con.sql(f"""
        SELECT count(*) AS players, sum(actions) AS actions,
               count(reep_id) AS has_reep,
               count(tm_player_id) AS has_tm,
               count(tm_name) AS tm_in_snapshot,
               sum(CASE WHEN tm_player_id IS NOT NULL THEN actions ELSE 0 END) AS actions_tm
        FROM '{OUT}'""").fetchone()
    players, actions, has_reep, has_tm, tm_in_snapshot, actions_tm = m

    # resolution is structurally different by gender: reep's statsbomb bridge and the
    # TM dataset are effectively men's-football-only — report the split, always
    side = con.sql(f"""
        WITH gender AS (
            SELECT DISTINCT competition_id, season_id,
                   competition_gender FROM read_json_auto(
                       '{ROOT / CFG["paths"]["statsbomb"]}/competitions.json')),
        pg AS (
            SELECT e.player_id,
                   max(CASE WHEN g.competition_gender = 'male' THEN 1 ELSE 0 END) AS mens
            FROM '{STAGING}/events/*.parquet' e
            JOIN gender g USING (competition_id, season_id)
            WHERE e.player_id IS NOT NULL GROUP BY e.player_id)
        SELECT CASE WHEN pg.mens = 1 THEN 'men' ELSE 'women' END AS side,
               count(*) AS players, count(m.tm_player_id) AS resolved
        FROM pg JOIN '{OUT}' m USING (player_id)
        GROUP BY 1 ORDER BY 1""").df()

    top_missing = con.sql(f"""
        SELECT player_id, player, actions FROM '{OUT}'
        WHERE tm_player_id IS NULL ORDER BY actions DESC LIMIT 50""").df()

    report = ROOT / CFG["paths"]["reports"] / "identity_resolution.md"
    lines = [
        "# Identity resolution (M2-T2)",
        "",
        "Regenerated by `src/harmonise/identity_join.py` on every `dvc repro`. Do not edit —",
        "hand-patches go in `src/harmonise/identity_overrides.csv` instead.",
        "",
        f"- corpus players (appear in events): **{players:,}**",
        f"- StatsBomb -> reep: {has_reep:,} ({has_reep / players:.1%})",
        f"- StatsBomb -> reep -> Transfermarkt: **{has_tm:,} ({has_tm / players:.1%})**",
        f"- action-weighted resolution: **{actions_tm / actions:.1%}** "
        "(misses concentrate in low-volume players if this is higher than the plain rate)",
        f"- resolved Transfermarkt ids present in our TM snapshot: {tm_in_snapshot:,} "
        f"of {has_tm:,}",
        "",
        "## By gender — the structural finding",
        "",
        "| side | players | resolved | rate |",
        "|---|--:|--:|--:|",
    ] + [
        f"| {r.side} | {int(r.players):,} | {int(r.resolved):,} "
        f"| {r.resolved / r.players:.1%} |"
        for _, r in side.iterrows()
    ] + [
        "",
        "Women's football is effectively absent from both the reep StatsBomb bridge and",
        "the Transfermarkt dataset, so Transfermarkt-derived labels (bios, transfer pairs",
        "for E5, appearance counts) are men-only. Market value is not among those labels —",
        "it was dropped from the project entirely (D13: country/league confounded). The",
        "quality axis is event-derived (VAEP / xG+xA), which every entity has. Women's",
        "data fully serves style training and the men->women transfer study (E8).",
        "Hand-patching (below) is therefore only meaningful for men's players.",
        "",
        "## Top 50 unresolved by actions (hand-patch candidates)",
        "",
        "| sb_player_id | player | actions |",
        "|--:|---|--:|",
    ]
    for _, r in top_missing.iterrows():
        lines.append(f"| {int(r.player_id)} | {r.player} | {int(r.actions):,} |")
    report.write_text("\n".join(lines) + "\n")

    print(f"{has_tm:,}/{players:,} resolved ({has_tm / players:.1%} plain, "
          f"{actions_tm / actions:.1%} action-weighted)")
    print(f"wrote {OUT.relative_to(ROOT)} and {report.relative_to(ROOT)}")
