"""Orientation assertion (M1-T10, PLAN §4.2): catch mirrored coordinates deliberately.

A coordinate-conversion bug produces plausible-looking output — a mirrored pitch is
still a pitch — so this asserts the one thing that cannot survive a mirror: shots
are taken near the goal being attacked (x -> 120). Runs per comp-season so a single
mirrored competition can't hide inside a healthy corpus average.

Writes reports/orientation_check.md; non-zero exit on any violation.
"""

import sys

import duckdb

from corpus import ROOT, load_config

CFG = load_config()
STAGING = ROOT / CFG["paths"]["staging"] / "statsbomb"

# a mirrored corpus would put the median shot around x = 20; a healthy one sits ~102.
# 60 = the loudest possible tripwire, not a tuning parameter. Tiny samples are noise.
MEDIAN_SHOT_X_FLOOR = 60
MIN_SHOTS = 20

if __name__ == "__main__":
    con = duckdb.connect()
    rows = con.sql(f"""
        SELECT competition_id, season_id, count(*) AS shots,
               median(x) AS med_x, avg(x) AS avg_x
        FROM '{STAGING}/events/*.parquet'
        WHERE type = 'Shot' AND period <= 4
        GROUP BY competition_id, season_id
        ORDER BY med_x
    """).df()

    checked = rows[rows.shots >= MIN_SHOTS]
    skipped = rows[rows.shots < MIN_SHOTS]
    bad = checked[checked.med_x < MEDIAN_SHOT_X_FLOOR]

    out = ROOT / CFG["paths"]["reports"] / "orientation_check.md"
    lines = [
        "# Orientation assertion (M1-T10)",
        "",
        "Regenerated by `src/ingest/orientation_check.py` on every `dvc repro`. Do not edit.",
        "",
        f"Rule: per comp-season with ≥ {MIN_SHOTS} shots, median shot x must be > "
        f"{MEDIAN_SHOT_X_FLOOR} (attack points at x = 120; a mirrored pitch would sit ~20).",
        "",
        f"- comp-seasons checked: {len(checked)} "
        f"(+{len(skipped)} below the {MIN_SHOTS}-shot floor, listed for the record)",
        f"- shot-weighted mean of the medians: "
        f"{(rows.shots * rows.med_x).sum() / rows.shots.sum():.1f}",
        f"- lowest comp-season median: {checked.med_x.min():.1f}, "
        f"highest: {checked.med_x.max():.1f}",
        "",
    ]
    if len(bad):
        lines.append(f"**{len(bad)} VIOLATION(S):**")
        for _, r in bad.iterrows():
            lines.append(f"- comp {int(r.competition_id)} season {int(r.season_id)}: "
                         f"median shot x = {r.med_x:.1f} over {int(r.shots)} shots")
    else:
        lines.append("**All checked comp-seasons pass.** No mirrored coordinates in staging.")
    if len(skipped):
        lines.append("")
        lines.append("Skipped (too few shots to judge): "
                     + ", ".join(f"{int(r.competition_id)}/{int(r.season_id)} ({int(r.shots)})"
                                 for _, r in skipped.iterrows()))

    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(ROOT)}")
    print(f"lowest median shot x: {checked.med_x.min():.1f} "
          f"({'FAIL' if len(bad) else 'pass'})")
    sys.exit(1 if len(bad) else 0)
