"""M4: cross-player nearest neighbours over the baseline style vectors.

The actual product query — "who plays like X?" — as cosine k-NN over the
z-scored residualized style features. Same position group by default; a
player's OTHER seasons are eligible and marked (self) — them ranking high is
the identity signal showing up in the product view, not a bug.

Importable for notebooks:  from neighbours import neighbours
Pipeline (__main__):       top-20 list per solid entity + showcase report.

Outputs:
  data/models/baseline_neighbours.parquet   (long: query keys, neighbour keys,
      rank, cosine — the table E1/E2 will score)
  reports/baseline_neighbours.md            (showcase queries for the eye test)
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "ingest"))
from corpus import ROOT, load_config  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
from trajectories import feature_cols, load_vectors  # noqa: E402

CFG = load_config()
OUT = ROOT / "data" / "models" / "baseline_neighbours.parquet"
MIN_MINUTES = 450
_CACHE = {}


def _prep(root):
    if "d" not in _CACHE:
        vec = load_vectors(root)
        solid = vec[vec.minutes >= MIN_MINUTES].reset_index(drop=True)
        X = solid[feature_cols(vec)].to_numpy(float)
        _CACHE["d"] = (solid, X / np.linalg.norm(X, axis=1, keepdims=True))
    return _CACHE["d"]


def neighbours(name, season=None, k=10, same_pos=True, root=ROOT):
    """Top-k stylistic neighbours of a player-season (default: their
    biggest-minutes season). Rows of the same player are marked, not hidden."""
    solid, N = _prep(root)
    cand = solid[solid.player.str.contains(name, case=False, na=False)]
    if season is not None:
        cand = cand[cand.season == season]
    if cand.empty:
        raise KeyError(f"no solid entity matching {name!r} / {season!r}")
    q = cand.minutes.idxmax()

    df = solid.assign(cosine=N @ N[q]).drop(index=q)
    if same_pos:
        df = df[df.pos_group == solid.pos_group[q]]
    out = df.nlargest(k, "cosine")[["player", "team", "season", "context",
                                    "pos_group", "minutes", "cosine"]].copy()
    out.insert(1, "self", df.loc[out.index, "player_id"] == solid.player_id[q])
    out.attrs["query"] = (f"{solid.player[q]} — {solid.team[q]} "
                          f"{solid.season[q]} ({solid.pos_group[q]})")
    return out


if __name__ == "__main__":
    solid, N = _prep(ROOT)
    S = N @ N.T
    np.fill_diagonal(S, -np.inf)
    K = 20
    top = np.argpartition(-S, K, axis=1)[:, :K]

    keys = solid[["player_id", "team_id", "season"]]
    rows = []
    for i in range(len(solid)):
        nb = top[i][np.argsort(-S[i, top[i]])]
        rows.append(pd.DataFrame({
            "q_player_id": keys.player_id[i], "q_team_id": keys.team_id[i],
            "q_season": keys.season[i],
            "n_player_id": keys.player_id.values[nb],
            "n_team_id": keys.team_id.values[nb], "n_season": keys.season.values[nb],
            "rank": np.arange(1, K + 1), "cosine": S[i, nb],
            "same_player": keys.player_id.values[nb] == keys.player_id[i],
        }))
    long = pd.concat(rows, ignore_index=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    long.to_parquet(OUT, compression="zstd", index=False)

    hit1 = long[long["rank"] == 1].same_player.mean()
    multi = solid.player_id.duplicated(keep=False)
    print(f"{len(solid):,} solid entities; rank-1 neighbour is the same player "
          f"for {hit1:.1%} of queries ({multi.mean():.1%} even have another season)")

    SHOWCASE = [("Messi Cuccittini", "2014/2015"), ("Iniesta", None),
                ("Piqué", None), ("Víctor Valdés", None),
                ("Samantha May Kerr", None)]
    report = ROOT / CFG["paths"]["reports"] / "baseline_neighbours.md"
    lines = [
        "# Baseline neighbour rankings (M4, z-score + cosine)",
        "",
        "Regenerated by `src/models/neighbours.py` on every `dvc repro`. Do not edit.",
        "",
        f"Entities with >= {MIN_MINUTES} min, same position group, cosine over the",
        "z-scored residualized style features. (self) = another season of the query",
        "player — those ranking high is the identity signal, reported not hidden.",
        "",
        f"Rank-1 neighbour is the same player in **{hit1:.1%}** of all "
        f"{len(solid):,} queries.",
    ]
    for name, season in SHOWCASE:
        t = neighbours(name, season, k=60)
        others = t[~t.self].drop_duplicates("player").head(8)
        n_self_above = int(t.self[:t.index.get_loc(others.index[0])].sum())
        lines += ["", f"## {t.attrs['query']}", "",
                  f"*{n_self_above} of their own seasons rank above the first "
                  f"other player.* Closest **other** players:", "",
                  "| player | team | season | cos |", "|---|---|---|--:|"]
        lines += [f"| {r.player} | {r.team} | {r.season} | {r.cosine:+.3f} |"
                  for r in others.itertuples()]
    report.write_text("\n".join(lines) + "\n")
    print(f"-> {OUT.relative_to(ROOT)}, {report.relative_to(ROOT)}")
